# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions: write-all


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        go build -v -o myapp ./...
        GOOS=windows GOARCH=amd64 go build -o sshhotspot-windows-amd64.exe ./...
        GOOS=linux GOARCH=amd64 go build -o sshhotspot-linux-amd64 ./...

    - name: Generate tag
      id: tag
      run: |
        echo "::set-output name=release_tag::release_$(date +%Y%m%d_%H%M%S)"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          sshhotspot-windows-amd64.exe
          sshhotspot-linux-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}